/*
Defect Dojo API v2

Defect Dojo - Open Source vulnerability Management made easy. Prefetch related parameters/responses not yet in the schema.

API version: 2.38.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package defectdojo

import (
	"encoding/json"
)

// checks if the PaginatedToolProductSettingsListPrefetch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedToolProductSettingsListPrefetch{}

// PaginatedToolProductSettingsListPrefetch struct for PaginatedToolProductSettingsListPrefetch
type PaginatedToolProductSettingsListPrefetch struct {
	Notes *map[string]Note `json:"notes,omitempty"`
	Product *map[string]Product `json:"product,omitempty"`
	ToolConfiguration *map[string]ToolConfiguration `json:"tool_configuration,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PaginatedToolProductSettingsListPrefetch PaginatedToolProductSettingsListPrefetch

// NewPaginatedToolProductSettingsListPrefetch instantiates a new PaginatedToolProductSettingsListPrefetch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedToolProductSettingsListPrefetch() *PaginatedToolProductSettingsListPrefetch {
	this := PaginatedToolProductSettingsListPrefetch{}
	return &this
}

// NewPaginatedToolProductSettingsListPrefetchWithDefaults instantiates a new PaginatedToolProductSettingsListPrefetch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedToolProductSettingsListPrefetchWithDefaults() *PaginatedToolProductSettingsListPrefetch {
	this := PaginatedToolProductSettingsListPrefetch{}
	return &this
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *PaginatedToolProductSettingsListPrefetch) GetNotes() map[string]Note {
	if o == nil || IsNil(o.Notes) {
		var ret map[string]Note
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedToolProductSettingsListPrefetch) GetNotesOk() (*map[string]Note, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *PaginatedToolProductSettingsListPrefetch) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given map[string]Note and assigns it to the Notes field.
func (o *PaginatedToolProductSettingsListPrefetch) SetNotes(v map[string]Note) {
	o.Notes = &v
}

// GetProduct returns the Product field value if set, zero value otherwise.
func (o *PaginatedToolProductSettingsListPrefetch) GetProduct() map[string]Product {
	if o == nil || IsNil(o.Product) {
		var ret map[string]Product
		return ret
	}
	return *o.Product
}

// GetProductOk returns a tuple with the Product field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedToolProductSettingsListPrefetch) GetProductOk() (*map[string]Product, bool) {
	if o == nil || IsNil(o.Product) {
		return nil, false
	}
	return o.Product, true
}

// HasProduct returns a boolean if a field has been set.
func (o *PaginatedToolProductSettingsListPrefetch) HasProduct() bool {
	if o != nil && !IsNil(o.Product) {
		return true
	}

	return false
}

// SetProduct gets a reference to the given map[string]Product and assigns it to the Product field.
func (o *PaginatedToolProductSettingsListPrefetch) SetProduct(v map[string]Product) {
	o.Product = &v
}

// GetToolConfiguration returns the ToolConfiguration field value if set, zero value otherwise.
func (o *PaginatedToolProductSettingsListPrefetch) GetToolConfiguration() map[string]ToolConfiguration {
	if o == nil || IsNil(o.ToolConfiguration) {
		var ret map[string]ToolConfiguration
		return ret
	}
	return *o.ToolConfiguration
}

// GetToolConfigurationOk returns a tuple with the ToolConfiguration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedToolProductSettingsListPrefetch) GetToolConfigurationOk() (*map[string]ToolConfiguration, bool) {
	if o == nil || IsNil(o.ToolConfiguration) {
		return nil, false
	}
	return o.ToolConfiguration, true
}

// HasToolConfiguration returns a boolean if a field has been set.
func (o *PaginatedToolProductSettingsListPrefetch) HasToolConfiguration() bool {
	if o != nil && !IsNil(o.ToolConfiguration) {
		return true
	}

	return false
}

// SetToolConfiguration gets a reference to the given map[string]ToolConfiguration and assigns it to the ToolConfiguration field.
func (o *PaginatedToolProductSettingsListPrefetch) SetToolConfiguration(v map[string]ToolConfiguration) {
	o.ToolConfiguration = &v
}

func (o PaginatedToolProductSettingsListPrefetch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedToolProductSettingsListPrefetch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	if !IsNil(o.Product) {
		toSerialize["product"] = o.Product
	}
	if !IsNil(o.ToolConfiguration) {
		toSerialize["tool_configuration"] = o.ToolConfiguration
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaginatedToolProductSettingsListPrefetch) UnmarshalJSON(data []byte) (err error) {
	varPaginatedToolProductSettingsListPrefetch := _PaginatedToolProductSettingsListPrefetch{}

	err = json.Unmarshal(data, &varPaginatedToolProductSettingsListPrefetch)

	if err != nil {
		return err
	}

	*o = PaginatedToolProductSettingsListPrefetch(varPaginatedToolProductSettingsListPrefetch)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "notes")
		delete(additionalProperties, "product")
		delete(additionalProperties, "tool_configuration")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaginatedToolProductSettingsListPrefetch struct {
	value *PaginatedToolProductSettingsListPrefetch
	isSet bool
}

func (v NullablePaginatedToolProductSettingsListPrefetch) Get() *PaginatedToolProductSettingsListPrefetch {
	return v.value
}

func (v *NullablePaginatedToolProductSettingsListPrefetch) Set(val *PaginatedToolProductSettingsListPrefetch) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedToolProductSettingsListPrefetch) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedToolProductSettingsListPrefetch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedToolProductSettingsListPrefetch(val *PaginatedToolProductSettingsListPrefetch) *NullablePaginatedToolProductSettingsListPrefetch {
	return &NullablePaginatedToolProductSettingsListPrefetch{value: val, isSet: true}
}

func (v NullablePaginatedToolProductSettingsListPrefetch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedToolProductSettingsListPrefetch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


