/*
Defect Dojo API v2

Defect Dojo - Open Source vulnerability Management made easy. Prefetch related parameters/responses not yet in the schema.

API version: 2.33.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package defectdojo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ToolConfigurationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ToolConfigurationRequest{}

// ToolConfigurationRequest struct for ToolConfigurationRequest
type ToolConfigurationRequest struct {
	Name string `json:"name"`
	Description NullableString `json:"description,omitempty"`
	Url NullableString `json:"url,omitempty"`
	// * `API` - API Key * `Password` - Username/Password * `SSH` - SSH
	AuthenticationType NullableString `json:"authentication_type,omitempty"`
	// Additional definitions that will be consumed by scanner
	Extras NullableString `json:"extras,omitempty"`
	Username NullableString `json:"username,omitempty"`
	Password NullableString `json:"password,omitempty"`
	AuthTitle NullableString `json:"auth_title,omitempty"`
	Ssh NullableString `json:"ssh,omitempty"`
	ApiKey NullableString `json:"api_key,omitempty"`
	ToolType int32 `json:"tool_type"`
}

type _ToolConfigurationRequest ToolConfigurationRequest

// NewToolConfigurationRequest instantiates a new ToolConfigurationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewToolConfigurationRequest(name string, toolType int32) *ToolConfigurationRequest {
	this := ToolConfigurationRequest{}
	this.Name = name
	this.ToolType = toolType
	return &this
}

// NewToolConfigurationRequestWithDefaults instantiates a new ToolConfigurationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewToolConfigurationRequestWithDefaults() *ToolConfigurationRequest {
	this := ToolConfigurationRequest{}
	return &this
}

// GetName returns the Name field value
func (o *ToolConfigurationRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ToolConfigurationRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ToolConfigurationRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ToolConfigurationRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ToolConfigurationRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *ToolConfigurationRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *ToolConfigurationRequest) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *ToolConfigurationRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *ToolConfigurationRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetUrl returns the Url field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ToolConfigurationRequest) GetUrl() string {
	if o == nil || IsNil(o.Url.Get()) {
		var ret string
		return ret
	}
	return *o.Url.Get()
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ToolConfigurationRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Url.Get(), o.Url.IsSet()
}

// HasUrl returns a boolean if a field has been set.
func (o *ToolConfigurationRequest) HasUrl() bool {
	if o != nil && o.Url.IsSet() {
		return true
	}

	return false
}

// SetUrl gets a reference to the given NullableString and assigns it to the Url field.
func (o *ToolConfigurationRequest) SetUrl(v string) {
	o.Url.Set(&v)
}
// SetUrlNil sets the value for Url to be an explicit nil
func (o *ToolConfigurationRequest) SetUrlNil() {
	o.Url.Set(nil)
}

// UnsetUrl ensures that no value is present for Url, not even an explicit nil
func (o *ToolConfigurationRequest) UnsetUrl() {
	o.Url.Unset()
}

// GetAuthenticationType returns the AuthenticationType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ToolConfigurationRequest) GetAuthenticationType() string {
	if o == nil || IsNil(o.AuthenticationType.Get()) {
		var ret string
		return ret
	}
	return *o.AuthenticationType.Get()
}

// GetAuthenticationTypeOk returns a tuple with the AuthenticationType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ToolConfigurationRequest) GetAuthenticationTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthenticationType.Get(), o.AuthenticationType.IsSet()
}

// HasAuthenticationType returns a boolean if a field has been set.
func (o *ToolConfigurationRequest) HasAuthenticationType() bool {
	if o != nil && o.AuthenticationType.IsSet() {
		return true
	}

	return false
}

// SetAuthenticationType gets a reference to the given NullableString and assigns it to the AuthenticationType field.
func (o *ToolConfigurationRequest) SetAuthenticationType(v string) {
	o.AuthenticationType.Set(&v)
}
// SetAuthenticationTypeNil sets the value for AuthenticationType to be an explicit nil
func (o *ToolConfigurationRequest) SetAuthenticationTypeNil() {
	o.AuthenticationType.Set(nil)
}

// UnsetAuthenticationType ensures that no value is present for AuthenticationType, not even an explicit nil
func (o *ToolConfigurationRequest) UnsetAuthenticationType() {
	o.AuthenticationType.Unset()
}

// GetExtras returns the Extras field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ToolConfigurationRequest) GetExtras() string {
	if o == nil || IsNil(o.Extras.Get()) {
		var ret string
		return ret
	}
	return *o.Extras.Get()
}

// GetExtrasOk returns a tuple with the Extras field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ToolConfigurationRequest) GetExtrasOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Extras.Get(), o.Extras.IsSet()
}

// HasExtras returns a boolean if a field has been set.
func (o *ToolConfigurationRequest) HasExtras() bool {
	if o != nil && o.Extras.IsSet() {
		return true
	}

	return false
}

// SetExtras gets a reference to the given NullableString and assigns it to the Extras field.
func (o *ToolConfigurationRequest) SetExtras(v string) {
	o.Extras.Set(&v)
}
// SetExtrasNil sets the value for Extras to be an explicit nil
func (o *ToolConfigurationRequest) SetExtrasNil() {
	o.Extras.Set(nil)
}

// UnsetExtras ensures that no value is present for Extras, not even an explicit nil
func (o *ToolConfigurationRequest) UnsetExtras() {
	o.Extras.Unset()
}

// GetUsername returns the Username field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ToolConfigurationRequest) GetUsername() string {
	if o == nil || IsNil(o.Username.Get()) {
		var ret string
		return ret
	}
	return *o.Username.Get()
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ToolConfigurationRequest) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Username.Get(), o.Username.IsSet()
}

// HasUsername returns a boolean if a field has been set.
func (o *ToolConfigurationRequest) HasUsername() bool {
	if o != nil && o.Username.IsSet() {
		return true
	}

	return false
}

// SetUsername gets a reference to the given NullableString and assigns it to the Username field.
func (o *ToolConfigurationRequest) SetUsername(v string) {
	o.Username.Set(&v)
}
// SetUsernameNil sets the value for Username to be an explicit nil
func (o *ToolConfigurationRequest) SetUsernameNil() {
	o.Username.Set(nil)
}

// UnsetUsername ensures that no value is present for Username, not even an explicit nil
func (o *ToolConfigurationRequest) UnsetUsername() {
	o.Username.Unset()
}

// GetPassword returns the Password field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ToolConfigurationRequest) GetPassword() string {
	if o == nil || IsNil(o.Password.Get()) {
		var ret string
		return ret
	}
	return *o.Password.Get()
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ToolConfigurationRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Password.Get(), o.Password.IsSet()
}

// HasPassword returns a boolean if a field has been set.
func (o *ToolConfigurationRequest) HasPassword() bool {
	if o != nil && o.Password.IsSet() {
		return true
	}

	return false
}

// SetPassword gets a reference to the given NullableString and assigns it to the Password field.
func (o *ToolConfigurationRequest) SetPassword(v string) {
	o.Password.Set(&v)
}
// SetPasswordNil sets the value for Password to be an explicit nil
func (o *ToolConfigurationRequest) SetPasswordNil() {
	o.Password.Set(nil)
}

// UnsetPassword ensures that no value is present for Password, not even an explicit nil
func (o *ToolConfigurationRequest) UnsetPassword() {
	o.Password.Unset()
}

// GetAuthTitle returns the AuthTitle field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ToolConfigurationRequest) GetAuthTitle() string {
	if o == nil || IsNil(o.AuthTitle.Get()) {
		var ret string
		return ret
	}
	return *o.AuthTitle.Get()
}

// GetAuthTitleOk returns a tuple with the AuthTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ToolConfigurationRequest) GetAuthTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthTitle.Get(), o.AuthTitle.IsSet()
}

// HasAuthTitle returns a boolean if a field has been set.
func (o *ToolConfigurationRequest) HasAuthTitle() bool {
	if o != nil && o.AuthTitle.IsSet() {
		return true
	}

	return false
}

// SetAuthTitle gets a reference to the given NullableString and assigns it to the AuthTitle field.
func (o *ToolConfigurationRequest) SetAuthTitle(v string) {
	o.AuthTitle.Set(&v)
}
// SetAuthTitleNil sets the value for AuthTitle to be an explicit nil
func (o *ToolConfigurationRequest) SetAuthTitleNil() {
	o.AuthTitle.Set(nil)
}

// UnsetAuthTitle ensures that no value is present for AuthTitle, not even an explicit nil
func (o *ToolConfigurationRequest) UnsetAuthTitle() {
	o.AuthTitle.Unset()
}

// GetSsh returns the Ssh field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ToolConfigurationRequest) GetSsh() string {
	if o == nil || IsNil(o.Ssh.Get()) {
		var ret string
		return ret
	}
	return *o.Ssh.Get()
}

// GetSshOk returns a tuple with the Ssh field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ToolConfigurationRequest) GetSshOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ssh.Get(), o.Ssh.IsSet()
}

// HasSsh returns a boolean if a field has been set.
func (o *ToolConfigurationRequest) HasSsh() bool {
	if o != nil && o.Ssh.IsSet() {
		return true
	}

	return false
}

// SetSsh gets a reference to the given NullableString and assigns it to the Ssh field.
func (o *ToolConfigurationRequest) SetSsh(v string) {
	o.Ssh.Set(&v)
}
// SetSshNil sets the value for Ssh to be an explicit nil
func (o *ToolConfigurationRequest) SetSshNil() {
	o.Ssh.Set(nil)
}

// UnsetSsh ensures that no value is present for Ssh, not even an explicit nil
func (o *ToolConfigurationRequest) UnsetSsh() {
	o.Ssh.Unset()
}

// GetApiKey returns the ApiKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ToolConfigurationRequest) GetApiKey() string {
	if o == nil || IsNil(o.ApiKey.Get()) {
		var ret string
		return ret
	}
	return *o.ApiKey.Get()
}

// GetApiKeyOk returns a tuple with the ApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ToolConfigurationRequest) GetApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApiKey.Get(), o.ApiKey.IsSet()
}

// HasApiKey returns a boolean if a field has been set.
func (o *ToolConfigurationRequest) HasApiKey() bool {
	if o != nil && o.ApiKey.IsSet() {
		return true
	}

	return false
}

// SetApiKey gets a reference to the given NullableString and assigns it to the ApiKey field.
func (o *ToolConfigurationRequest) SetApiKey(v string) {
	o.ApiKey.Set(&v)
}
// SetApiKeyNil sets the value for ApiKey to be an explicit nil
func (o *ToolConfigurationRequest) SetApiKeyNil() {
	o.ApiKey.Set(nil)
}

// UnsetApiKey ensures that no value is present for ApiKey, not even an explicit nil
func (o *ToolConfigurationRequest) UnsetApiKey() {
	o.ApiKey.Unset()
}

// GetToolType returns the ToolType field value
func (o *ToolConfigurationRequest) GetToolType() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ToolType
}

// GetToolTypeOk returns a tuple with the ToolType field value
// and a boolean to check if the value has been set.
func (o *ToolConfigurationRequest) GetToolTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToolType, true
}

// SetToolType sets field value
func (o *ToolConfigurationRequest) SetToolType(v int32) {
	o.ToolType = v
}

func (o ToolConfigurationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ToolConfigurationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Url.IsSet() {
		toSerialize["url"] = o.Url.Get()
	}
	if o.AuthenticationType.IsSet() {
		toSerialize["authentication_type"] = o.AuthenticationType.Get()
	}
	if o.Extras.IsSet() {
		toSerialize["extras"] = o.Extras.Get()
	}
	if o.Username.IsSet() {
		toSerialize["username"] = o.Username.Get()
	}
	if o.Password.IsSet() {
		toSerialize["password"] = o.Password.Get()
	}
	if o.AuthTitle.IsSet() {
		toSerialize["auth_title"] = o.AuthTitle.Get()
	}
	if o.Ssh.IsSet() {
		toSerialize["ssh"] = o.Ssh.Get()
	}
	if o.ApiKey.IsSet() {
		toSerialize["api_key"] = o.ApiKey.Get()
	}
	toSerialize["tool_type"] = o.ToolType
	return toSerialize, nil
}

func (o *ToolConfigurationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"tool_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varToolConfigurationRequest := _ToolConfigurationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varToolConfigurationRequest)

	if err != nil {
		return err
	}

	*o = ToolConfigurationRequest(varToolConfigurationRequest)

	return err
}

type NullableToolConfigurationRequest struct {
	value *ToolConfigurationRequest
	isSet bool
}

func (v NullableToolConfigurationRequest) Get() *ToolConfigurationRequest {
	return v.value
}

func (v *NullableToolConfigurationRequest) Set(val *ToolConfigurationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableToolConfigurationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableToolConfigurationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableToolConfigurationRequest(val *ToolConfigurationRequest) *NullableToolConfigurationRequest {
	return &NullableToolConfigurationRequest{value: val, isSet: true}
}

func (v NullableToolConfigurationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableToolConfigurationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


